spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 10000
    # 如果Redis需要密码，请取消下面的注释并设置密码
    password: 123456

easy:
  lock:
    enabled: true
    prefix: easy:lock:test
    expireTime: 30000
    retryCount: 3
    retryInterval: 100
    monitorEnabled: true 